// Code generated by Slice Machine. DO NOT EDIT.

import Hero from "./Hero/index.svelte";
import MediaText from "./MediaText/index.svelte";
import RichText from "./RichText/index.svelte";

export const components = {
  hero: Hero,
  media_text: MediaText,
  rich_text: RichText,
};
